---
- name: Configurar servidor Ubuntu para MariaDB
  hosts: ubuntu
  become: yes

  tasks:
    - name: Actualizar caché de paquetes
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar Python 3
      ansible.builtin.apt:
        name: python3
        state: present

    - name: Instalar python3-pymysql
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: Instalar pip
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Instalar MariaDB
      ansible.builtin.apt:
        name: mariadb-server
        state: present
      register: install_result
      changed_when: install_result.changed

    - name: Asegurar MariaDB con mysql_secure_installation
      ansible.builtin.command:
        cmd: mysql_secure_installation
        stdin: |
          ''
          Y
          prueba2024
          prueba2024
          n
          y
          y
          y
          y
      when: install_result.changed

    - name: Asegurarse de que MariaDB esté en funcionamiento
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: Permitir acceso a MariaDB en el firewall
      community.general.ufw:
        rule: allow
        port: '3306'
        proto: tcp
        state: enabled

    - name: Crear base de datos "todo"
      community.mysql.mysql_db:
        login_user: root
        login_password: prueba2024
        name: todo
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Crear usuario 'todo'
      community.mysql.mysql_user:
        name: todo
        password: prueba2024
        priv: 'todo.*: ALL,GRANT'
        state: present
        login_user: root
        host: '%'
        login_password: prueba2024

    - name: Crear tabla 'users'
      community.mysql.mysql_query:
        login_user: root
        login_password: prueba2024
        login_db: todo
        query: |
          CREATE TABLE `users` (
            `id` int(3) NOT NULL AUTO_INCREMENT,
            `first_name` varchar(20) DEFAULT NULL,
            `last_name` varchar(20) DEFAULT NULL,
            `username` varchar(250) DEFAULT NULL,
            `password` varchar(20) DEFAULT NULL,
            PRIMARY KEY (`id`)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

    - name: Crear tabla 'todos'
      community.mysql.mysql_query:
        login_user: root
        login_password: prueba2024
        login_db: todo
        query: |
          CREATE TABLE `todos` (
            `id` bigint(20) NOT NULL AUTO_INCREMENT,
            `description` varchar(255) DEFAULT NULL,
            `is_done` bit(1) NOT NULL,
            `target_date` datetime(6) DEFAULT NULL,
            `username` varchar(255) DEFAULT NULL,
            `title` varchar(255) DEFAULT NULL,
            PRIMARY KEY (`id`)
          ) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;