---
- name: imprimir ansible facts
  hosts: linux
  gather_facts: yes
  become: false
  user: agonzalez

  tasks:
  - name: imprimir familia
    debug: msg="{{ ansible_os_family }}"
  - name: imprimir Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"