---
- name: hardening SSH de servers
  hosts: linux
  become: yes
  user: agonzalez

  tasks:

  - name: Quito login root
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#PermitRootLogin'
      line: PermitRootLogin no
    notify: 
      - reiniciar SSH Ubuntu
      - reiniciar SSH CentOS
  
  handlers:

  - name: reiniciar SSH Ubuntu
    ansible.builtin.service:
      state: restarted
      name: ssh
    when: ansible_facts['os_family'] == "Debian"


  - name: reiniciar SSH CentOS
    ansible.builtin.service:
      state: restarted
      name: sshd
    when: ansible_facts['os_family'] == "RedHat"    